### ISSUE TITLE
typescript build error

### ISSUE THREAD

**Issue by Fauziku2** [webcat12345/ngx-ui-switch#132]
Hi,

First, thanks for the great component.
When building I am getting this error:

`ERROR in ./~/ngx-ui-switch/src/index.ts
Module build failed: Error: Typescript emitted no output for /Users/Fauzi/code/mx/maritimexchange/node_modules/ngx-ui-switch/src/index.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at Object.loader (/Users/Fauzi/code/mx/maritimexchange/node_modules/ts-loader/dist/index.js:32:15)
 @ ./src/common/common.module.ts 22:12-40
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.ts
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 519 bytes [entry]
webpack: Failed to compile.`

Could you help please?

**Comment by cmckni3** [comment]
The project actually needs a build process. The current build process doesn't build the library correctly for use with Angular. I made a fix to the README in my fork but got an error about using the main file, `dist/index.js`.

I am going to work on a build process and send a PR if that's ok with you, @webcat12345.

**Comment by webcat12345** [comment]
Thanks @cmckni3 , That works for me. I created this component with basic feature only and really welcome PR in order to improve this component.
