### ISSUE TITLE
Getting ERROR in UiSwitchModule is not an NgModule in Angular 4.0.0

### ISSUE THREAD

**Issue by Sathishchary** [webcat12345/ngx-ui-switch#15]
I am getting UiSwitchModule is not an NgModule in run time 
I have imported like this
import { UiSwitchModule } from 'ngx-ui-switch';
and:
imports: [
BrowserModule,
ReactiveFormsModule,
FormsModule,
HttpModule,
UiSwitchModule ,
],

**Comment by webcat12345** [comment]
```import { UiSwitchModule } from 'ngx-ui-switch/src';```

**Comment by Sathishchary** [comment]
thanks for the reply. It's working fine

**Comment by kamalakkanni** [comment]
hi,I got error as cannot find module 'ngx-ui-switch/src'; while using 
 import { UiSwitchModule } from 'ngx-ui-switch/src';.can you pls help me
