### ISSUE TITLE
Add contributor section in README

### ISSUE THREAD

**Issue by webcat12345** [webcat12345/ngx-ui-switch#184]
In order to increase activity of communication, it is needed to add contributor section inside Doc.

**Comment by cmckni3** [comment]
Should this be how to contribute or just the names/GitHub handles of all repo contributors?

**Comment by cmckni3** [comment]
I think we should cleanup the README as well. The examples take up a lot of room.

**Comment by cmckni3** [comment]
Let me know if you want something more @webcat12345. I can reopen this issue.
