### ISSUE TITLE
cannot find module 'ngx-ui-switch/src'

### ISSUE THREAD

**Issue by kamalakkanni** [webcat12345/ngx-ui-switch#218]
hi,

I got error as  Unexpected module 'UiSwitchModule' while running ng build --prod which is working fine in ng serve.so that I imported ngx-ui-switch/src as per https://github.com/webcat12345/ngx-ui-switch/issues/15#issuecomment-295628177 .But I got cannot find module ngx-ui-switch/src error.

Thanks

**Comment by kamalakkanni** [comment]
Its working fine while using ngx-ui-switch itself

**Comment by vin0010** [comment]
Its not working for me even if I use ngx-ui-switch. A ny thoughts?

**Comment by cmckni3** [comment]
What happens @vin0010? Error message?

**Comment by vin0010** [comment]
Thank you @cmckni3 It was a minor build issue, resolved. Thank you so much.
