### ISSUE TITLE
MetaData version mismatch error with version 1.4.9

### ISSUE THREAD

**Issue by rahultokase** [webcat12345/ngx-ui-switch#219]
HI 
With the latest version of ngx-ui-switch@1.4.9 and angular 4 application I am getting metadata version mismatch error for this module

C:/mywork/Personnel/mystuff/thirdparty/engage/node_modules/ngx-ui-switch/index.d.ts, found versio
n 4, expected 3,

I am using angular cli 1.4.5 version.

can you please share  the dependency (that now depends on Angular 5) to the prior version that is compatible with Angular 4. ?

**Comment by cmckni3** [comment]
Try version `1.4.4`

**Comment by rahultokase** [comment]
Thanks its working fine . Just a one suggestion cant we have 1.5.X version for angular 5 and 1.4.X version for angular 4.

**Comment by cmckni3** [comment]
I agree that it's confusing. Really 1.4.x should work on 2+ but that isn't the case due to how the Angular compiler works.

I will make a note of this for future releases.

**Comment by cmckni3** [comment]
I deprecated 1.4.5-1.4.9 and switched to 2.0.0 for Angular v5. I am updating the documentation right now as well. Angular v4 is now `ngx-ui-switch@^1.5.0`

**Comment by cmckni3** [comment]
Documentation updated

**Comment by aviaur** [comment]
Sorry but it doesn't work ngx-ui-switch 1.5.0 with Angular4...
ERROR in Error: Metadata version mismatch for module ...... found version 4, expected 3 ......

With version 1.4.4 it works.

**Comment by cmckni3** [comment]
ugh I'll install ng 4 again and see what the issue is.

Your versions all aligned to the same version of 4 right @aviaur?

**Comment by aviaur** [comment]
Yes I am on version 4.4.6 of Angular

**Comment by cmckni3** [comment]
Try 1.6.0 @aviaur. I downgraded `ts-node` and some other dependencies to what it was on 1.4.4. I also tried it in a sample app using ng 4.4.6.

**Comment by aviaur** [comment]
I don't understand but i don't find the version 1.6.0 with yarn install...

![image](https://user-images.githubusercontent.com/37070195/37023001-e38d3fd4-2124-11e8-956f-1f2ac8727406.png)
