### ISSUE TITLE
ngModel' since it isn't a known property of 'ui-switch'

### ISSUE THREAD

**Issue by javascriptDC** [webcat12345/ngx-ui-switch#227]
`ngModel` is not working properly.
Issue: 
compiler.es5.js:1694 Uncaught Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'ui-switch'.
1. If 'ui-switch' is an Angular component and it has 'ngModel' input, then verify that it is part of this module.
2. If 'ui-switch' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. 
            
            <ui-switch [ERROR ->][(ngModel)]="enable"></ui-switch>
          </div>

```html
<ui-switch [(ngModel)]="enable"></ui-switch>
```
```javascript
enable = true;
```

**Comment by javascriptDC** [comment]
I downgrade this module into 1.4.4 because of MetaData version mismatch error with version 1.4.9.

Could you provide any good solution with me, please?

**Comment by cmckni3** [comment]
This may have been what I was talking about in #189

**Comment by javascriptDC** [comment]
When downgrading it into 1.4.4, the two-way binding is not working.

**Comment by cmckni3** [comment]
Can't reproduce on 1.5.0. The demo works fine in the 1.x-stable branch with Angular 4.

Have you imported the module `UiSwitchModule`?

**Comment by vinayadepu** [comment]
1. Point properly ngx-ui-swith module in app.module
such as 
import { UiSwitchModule } from '../../node_modules/ngx-ui-switch';
2. set ".css" file in style.css as below:
 "styles": [
              "node_modules/ngx-ui-switch/ui-switch.component.css"
            ],

**Comment by cmckni3** [comment]
@vinayadepu that import is not correct and those instructions are in the README

**Comment by FinlayDaG33k** [comment]
Sorry for necro'ing this issue but I want to point out for people coming by here that one can also import it in the `shared.module.ts` to have it available for all components.  

```ts
// shared.module.ts
import { UiSwitchModule } from 'ngx-toggle-switch';

@NgModule({
  imports: [UiSwitchModule, ...],
  exports: [UiSwitchModule, ...]
})
export class SharedModule{}
```
