### ISSUE TITLE
ERROR in UiSwitchModule is not an NgModule

### ISSUE THREAD

**Issue by kovorka** [webcat12345/ngx-ui-switch#23]
I was previously running the angular2-ui-switch (https://www.npmjs.com/package/angular2-ui-switch).

I installed the ngx-ui-switch, changed my module to: import { UiSwitchModule } from 'ngx-ui-switch';

I get the same error as I did with the previous switchModule either trying to build or use WebPack: ERROR in UiSwitchModule is not an NgModule

Does this switch have any dependencies? Do I need to clear some cache thing perhaps?

**Comment by webcat12345** [comment]
https://github.com/webcat12345/ngx-ui-switch/issues/15

Duplicate issue. I will update ReadME.md

**Comment by webcat12345** [comment]
If it works, please let me know, then I will close this issue.

**Comment by kovorka** [comment]
works with webpack and build --aot

deploying now ;D
