### ISSUE TITLE
Set up global settings

### ISSUE THREAD

**Issue by AlexanderKozhevin** [webcat12345/ngx-ui-switch#252]
Can we set global settings?
Like this
```JavaScript
UiSwitchModule.forRoot({
   color: '#FF5800'
})
```

**Comment by cmckni3** [comment]
As of right now, no. I can add it when I have a chance. PRs welcome.

**Comment by cmckni3** [comment]
Released in 2.2.0

**Comment by AlexanderKozhevin** [comment]
@cmckni3 Thanx, awesome!

**Comment by cmckni3** [comment]
No problem.

@kubiq implemented it today. I merged and released
