### ISSUE TITLE
 Option to turn off inline CSS

### ISSUE THREAD

**Issue by CmajSmith** [webcat12345/ngx-ui-switch#287]
Hello. First of all thanks for all your work on this awesome component. 

I'm currently working on a project that has a very strict [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) (has `style-src` set to `'self'`), which totally blocks ngx-ui-switch display as it inserts inline styles. 

So, the suggestion is to add an option that allows turning the inline CSS addition off, and let the controls rely on outer CSS-files rules only.

**Comment by cmckni3** [comment]
I started this a while back. I'll see if I can pick it back up in #242

**Comment by CmajSmith** [comment]
I could give it a try if you don't mind. Both this one and #242.

**Comment by cmckni3** [comment]
Go for it. This is a duplicate issue of #188 and should be done with #247 if possible.

**Comment by CmajSmith** [comment]
Please check the pull request once you'll have time for it. 

I'd handle #247 separately as it definitely shouldn't be added with CSS (in my opinion) as was initially proposed in issue description.

**Comment by cmckni3** [comment]
Well yeah it shouldn't be added with CSS. But the structure was going to have to change to support to text.
