### ISSUE TITLE
Label Text on Button

### ISSUE THREAD

**Issue by LiveAction-SunArc-Op** [webcat12345/ngx-ui-switch#296]
I would like to use labels on button, similar to <ui-switch labelOn="Yes" labelOff="No"></ui-switch> in ngx-toggle-switch

**Comment by cmckni3** [comment]
Updating the docs right now. About to publish 6.1.0.

**Comment by LiveAction-SunArc-Op** [comment]
Hey Chris McKnight, after upgrading my npm to 6.1.0, I lost the toggle switch. I added the labels only labels were displayed.

**Comment by cmckni3** [comment]
Yeah, the styling has been separated out. You'll need the default CSS/SCSS file.

**Comment by LiveAction-SunArc-Op** [comment]
I was able to import the style sheet from your src. the label is now getting displayed along with switch. Thanks, Team
