### ISSUE TITLE
Broken after upgrading from 6.0.3 to 6.1.1

### ISSUE THREAD

**Issue by ShinDarth** [webcat12345/ngx-ui-switch#297]
I've updated my project to use version `6.1.1` (previously I had `6.0.3`) and all switches disappeared with no errors in the console.

The `<ui-switch>` elements are still in the DOM but they have 0x0 dimensions.

Reverting to version `6.0.3` solves the issue for me.

**Comment by cmckni3** [comment]
Include the SCSS/CSS

**Comment by cmckni3** [comment]
I’ll yank the 6.1 releases and release 7.0 since this is an issue.

**Comment by ShinDarth** [comment]
@cmckni3 I've tried that and still didn't work

**Comment by cmckni3** [comment]
Can you reproduce in stackblitz?

**Comment by ShinDarth** [comment]
@cmckni3 sure, can you give me a template?

**Comment by ShinDarth** [comment]
I use it with ReactiveForms and it looks like working here: https://stackblitz.com/edit/ngx-ui-switch-whhxxq

So I still don't know what in my codebase is causing the issue but, whatever it is, it's only affecting the newer release version. 

I'll further investigate the issue, hoping to reproduce it in a separate environment.

**Comment by ShinDarth** [comment]
@cmckni3 the issue is the following:

for some reasons if I include the style in a scss file using:

`@import '~ngx-ui-switch/ui-switch.component.scss';`

then it works. But if I include it in my `angular.json` (and restart `ng serve`) then it does not work (I've tried both `css` and `scss` files, same problems).

**Comment by cmckni3** [comment]
What does `styles` for your application in `angular.json` look like? [This](https://stackblitz.com/edit/ngx-ui-switch-tabu3h?file=angular.json) works for me.

**Comment by ShinDarth** [comment]
@cmckni3 I've just realised that I was adding the style to a wrong style set. Everything works fine. Sorry for the confusion.
