### ISSUE TITLE
Globally setting labels does not work (7.0.0)

### ISSUE THREAD

**Issue by rmcsharry** [webcat12345/ngx-ui-switch#299]
I can set labels on individual switches in a template, but when I try to set them globally they are ignored:

```
    UiSwitchModule.forRoot({
      color: '#cbffcb',
      switchColor: '#a69986',
      defaultBgColor: '#fff',
      defaultBoColor: '#ab9885', 
      checkedLabel: 'Yes',
      uncheckedLabel: 'No'      
    }),
```

**Comment by cmckni3** [comment]
Ah I see the issue. The interface was updated but not the code. Oops. I’ll fix it and publish tonight.

**Comment by cmckni3** [comment]
7.0.1 published to npm

**Comment by rmcsharry** [comment]
@cmckni3 Thank you for the fast fix, very much appreciated 👍
