### ISSUE TITLE
when untouched, getting empty string instead of false when used in form [demo]

### ISSUE THREAD

**Issue by goodmite** [webcat12345/ngx-ui-switch#300]
When I am using ui-switch inside of a form, I am getting form value as `{ "enabled": "" }`, instead of `{ "enabled": false}`, when form is untouched. 

[Demo on stackblitz]( https://stackblitz.com/edit/ngx-ui-switch-stetuv)

Any suggestions?

**Comment by cmckni3** [comment]
Interesting. That's something to do with the value of the control and binding with `NgForm`.

What's the use case here? Are you wanting to use the value of the form object of `NgForm`?

**Comment by sangupta007** [comment]
Yes, I want to use the `value` of the form object of `NgForm`?

**Comment by cmckni3** [comment]
Fixed in 10.0.1
