### ISSUE TITLE
Extend peer dependencies to Angular 7 

### ISSUE THREAD

**Issue by agil-NUBBA** [webcat12345/ngx-ui-switch#302]
**Issue description**

running `npm install` throws the following warning:

```
npm WARN ngx-ui-switch@7.0.1 requires a peer of @angular/core@>=5.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-ui-switch@7.0.1 requires a peer of @angular/common@>=5.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-ui-switch@7.0.1 requires a peer of @angular/forms@>=5.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
```
**Steps to reproduce and a minimal demo of the problem**

`npm install` with Angular 7

**Current behavior**

`npm install` shows a couple of warning due to peer dependencies.

**Expected/desired behavior**

No warnings should be shown

**Comment by cmckni3** [comment]
8.0.0-beta.0 published to npmjs.org
