### ISSUE TITLE
Label Example

### ISSUE THREAD

**Issue by Velocity540** [webcat12345/ngx-ui-switch#307]
do you have an example of an inline label next to a switch? One that connects to the sate of the switch, and can set the switch  True and False?

**Comment by cmckni3** [comment]
not exactly sure what you mean.

Do you mean something like this?

```
<label>
  Enable feature?
  <ui-switch></ui-switch>
</label>
```

**Comment by cmckni3** [comment]
Best thing I can come up with for now is:

```
<label (click)="enable = !enable">
  Enable feature?
  <ui-switch [(ngModel)]="enable"></ui-switch>
</label>
```
