### ISSUE TITLE
Incompatible peer dependencies found. RXJS

### ISSUE THREAD

**Issue by fromage9747** [webcat12345/ngx-ui-switch#308]
When running: ng update @angular/cli @angular/core
on the latest version of RXjS I get the below:
Package "ngx-ui-switch" has an incompatible peer dependency to "rxjs" (requires "^5.4.0", would install "6.3.3").

**Comment by cmckni3** [comment]
Are you upgrading from a 6.x release of `ngx-ui-switch`?

**Comment by cmckni3** [comment]
Specifically [6.0.2](https://github.com/webcat12345/ngx-ui-switch/compare/6.0.1...6.0.2) removed the unnecessary peer dependency on rxjs.

Give a npm/yarn update to 6.1.1 a try first.
