### ISSUE TITLE
 checkedLabel &  uncheckedLabel doesn't work for version 1.6.1 in Angular4

### ISSUE THREAD

**Issue by sumandeepkaur01** [webcat12345/ngx-ui-switch#309]
My application is on Angular 4 and I am using  " ngx-ui-switch: 1.6.1".I can't use properties checkedLabel &  uncheckedLabel in my code.Is it provided or not for this particular version ?

**Comment by cmckni3** [comment]
it's not available 1.x. It's available in 6.1.0 and up.

Sorry about that. Will get a changelog going soon

**Comment by sumandeepkaur01** [comment]
oops...that is a useful property, will be waiting for it. :)
Really appreciate the quick response.

**Comment by cmckni3** [comment]
hmm the latest versions of ngx-ui-switch have diverged quite a bit from 1.x.

Have you looked into updating to ng 5 at least? There's an issue with ng metadata so 1.x will not work with 5+ and vice versa.

I would consider [upgrading](https://update.angular.io)
