### ISSUE TITLE
Remove greenkeeper

### ISSUE THREAD

**Issue by cmckni3** [webcat12345/ngx-ui-switch#316]
Remove greenkeeper app from project. I would rather use renovate and snyk.

**Comment by webcat12345** [comment]
`greenkeeper` already uninstalled from the repository. 

![image](https://user-images.githubusercontent.com/19761422/52188914-3cf48880-27ea-11e9-9b5d-e841875b1e10.png)

We just need to remove `greenkeeper` options from `package.json` and Travis config

**Comment by webcat12345** [comment]
`renovate` and `snyk` installed. @cmckni3 can you please let me know your email address to add to `synk`?

**Comment by cmckni3** [comment]
@webcat12345 sure, it's cmckni3 [at] gmail.com

**Comment by webcat12345** [comment]
@cmckni3 invite sent to you.

**Comment by webcat12345** [comment]
Btw, synk is having some trouble now. https://snyk.statuspage.io/

**Comment by cmckni3** [comment]
Accepted it 👍
