### ISSUE TITLE
Edge browser issue

### ISSUE THREAD

**Issue by BullFrog13** [webcat12345/ngx-ui-switch#332]
It seems like the switch does not work for Edge browser as expected. When switched from on to off the <small> element does not switch to left side. It seems like the browser does not see class changes on the element for some reason and does not apply styles.

**Comment by BullFrog13** [comment]
![screenshot_1](https://user-images.githubusercontent.com/14280303/53814444-9e189480-3f2d-11e9-8303-555070bf51c6.png)
![1](https://user-images.githubusercontent.com/14280303/53814445-9e189480-3f2d-11e9-99c9-72683aa30ed8.png)

**Comment by cmckni3** [comment]
I'll have to take a look at some point.

Does the [stackblitz demo](https://webcat12345.github.io/ngx-ui-switch/demo/) have the issue?

Can you share your `polyfills.ts`?

**Comment by BullFrog13** [comment]
Yes, stakblitz demo has issues for all switches in the latest Edge version.

In order to fix the problem you need to rearrange **&.checked small**  section in your scss file.
For me this has done the trick. Did not encounter any issues so far in both Chrome and Edge.

![Screenshot](https://user-images.githubusercontent.com/14280303/54393412-78536400-4680-11e9-83ac-14e046eae343.png)

It seems that the reason for this is how Edge hooks the styles and classes when you change them dynamically.

If you are curious try to open switch in developer tools  in Edge and navigate to 
`<span class="switch switch-medium checked"></span>`

When you switch off the element and see this issue select **span**  in the developer console.
This will trigger styles update for span.

This is Edge known issue: [link](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/935871/)

**Comment by cmckni3** [comment]
8.0.1 released

Tested in latest Edge and Chrome.

Let me know if you have anymore issues
