### ISSUE TITLE
Change value, programatically

### ISSUE THREAD

**Issue by acegilz** [webcat12345/ngx-ui-switch#337]
I would like to know the easiest way to change value of switcher programatically.
The reason why I want this is the following:

- User clicks on the switch (lets say inactive to active - false to true)
- An asynchronous request is made to the server (change function) 
- If response comes {success: false} (unauthorised) I want the put value of switcher back to correct (on the server response) {correct_val: xxxx}

**Comment by cmckni3** [comment]
I use `[(ngModel)]="settings.developerMode"` in the template. Then update the `settings` component property when the server response comes back. I use `catchError` to switch to the previous value.
