### ISSUE TITLE
Using version 1.6.0 - checkedLabel and uncheckedLabel won't work

### ISSUE THREAD

**Issue by artaniszeratul** [webcat12345/ngx-ui-switch#343]
Hi

I am using version 1.6.0 but checkedLabel and uncheckedLabel won't work
There is no label in the "On" or "Off label doesn't show up."

Here is my HTML code snippet: <ui-switch checkedLabel="on" uncheckedLabel="off">Test</ui-switch>

**Comment by cmckni3** [comment]
https://github.com/webcat12345/ngx-ui-switch/issues/309

**Comment by cmckni3** [comment]
PR against 1.x-stable to backport functionality welcome.
