### ISSUE TITLE
how to fix this warn

### ISSUE THREAD

**Issue by MansoorJafari9** [webcat12345/ngx-ui-switch#356]
hello 
how to fix this warn after npm install

npm WARN ngx-ui-switch@1.6.1 requires a peer of @angular/core@>=4.0.0 < 5.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by cmckni3** [comment]
What version of Angular are you running?

**Comment by MansoorJafari9** [comment]
"@angular/cli": "~7.3.8",

**Comment by cmckni3** [comment]
That's only the version the cli but I'm guessing you have 7.x for all `@angular/*` dependencies.

To fix the warning, you need to update to a newer version of ngx-ui-switch. Otherwise, you can ignore it due to Angular major versions being mostly backwards compatibility.

```
"ngx-ui-switch": "^8.0.0"
```
