### ISSUE TITLE
Properties checkedTextColor/uncheckedTextColor don't exist in v8.2.0 from npm

### ISSUE THREAD

**Issue by alpinx** [webcat12345/ngx-ui-switch#377]
I can see them on the demo page, but when I install 8.2.0 version through the npm, this properties don't exist in the code

@gregoryalary, please can you take a look?

**Comment by gregoryalary** [comment]
Hey @alpinx, I think that the new version has not been published to npm yet and I don't have the rights to do it. @cmckni3, can you confirm and/or publish it ?

**Comment by cmckni3** [comment]
8.3.0 published

**Comment by gregoryalary** [comment]
Thanks @cmckni3 !

**Comment by alpinx** [comment]
Thanks, appreciate it
