### ISSUE TITLE
reverse attribute question

### ISSUE THREAD

**Issue by BrutalCSkakan** [webcat12345/ngx-ui-switch#382]
Hello! 
What is the intended way of "reverse"? 
I currently have a boolean coming from a backend with "false" as the value, which causes the switch to be in "off" mode.
I want to reverse this, so that the switch is "on" when its value is false.

Is this what "reverse" should do? If that's the case, then I think it's broken.

**Comment by cmckni3** [comment]
Disabled and reverse are broken I think.

PRs welcome

**Comment by cmckni3** [comment]
The actual behavior of reverse is to reverse the colors that are specified via the component or global options.

By default that won't happen because the component is styled via CSS.
