### ISSUE TITLE
switch is submitting form

### ISSUE THREAD

**Issue by knpaing** [webcat12345/ngx-ui-switch#395]
Hi,

ui-switch was working great till I've updated to this latest version. I'm using it inside a reactive form and now whenever user click the switch, it will just submit the form. My form is using (ngSubmit) event. Since the button inside ui-switch does not define it's type (I guess) it is causing the form to submit. Please find the screenshot below:

<img width="1080" alt="Screen Shot 2020-03-05 at 1 33 56 AM" src="https://user-images.githubusercontent.com/12625702/75913757-e42a7000-5e81-11ea-986f-6608f5444568.png">

**Comment by cmckni3** [comment]
Probably due to accessibility change. Span was changed to button.

**Comment by knpaing** [comment]
> Probably due to accessibility change. Span was changed to button.

Yup. I checked previous was using span. Had to rollback to 8.3.0 for now.

**Comment by cmckni3** [comment]
Made PR to add type=button. Should fix it.

**Comment by cmckni3** [comment]
I asked for feedback in #394 but npm probably suppresses the beta updates.

**Comment by cmckni3** [comment]
Added an example to the demo and released 9.0.1

**Comment by knpaing** [comment]
Thanks. It's all good now. :)
