### ISSUE TITLE
Keypress in other controls triggering switch

### ISSUE THREAD

**Issue by knpaing** [webcat12345/ngx-ui-switch#397]
Hi,

Thanks for the quick fixed on "button" problem. Here is another one I've encountered afterwards.

Whenever the switch is set to "true", and you press a key in different controls inside the form, the switch set back to 'false' automatically. Pls check the attached short video clip for clear reference.

![Screen-Recording-2020-03-06-at-12 21 12-AM](https://user-images.githubusercontent.com/12625702/76010499-60d05380-5f41-11ea-9a1a-d3e71b921b63.gif)

**Comment by cmckni3** [comment]
I will see if I can investigate this weekend.

I think it’s due to the behavior of html buttons.

PRs welcome

**Comment by cmckni3** [comment]
@knpaing are you able to provide an example to reproduce?

I couldn't reproduce it in the demo sandbox. See my [commit to update the demo](https://github.com/webcat12345/ngx-ui-switch/commit/f0fefd4e69aba812e9cf6505dd94acbc6781656e)

**Comment by knpaing** [comment]
@cmckni3 I'm sorry to say that it was caused by my code. Somewhere in my code keep pushing the switch to "false"/"unchecked" state. Please close this topic as this is no longer issue. Thanks for your time.
