### ISSUE TITLE
beforeChange fires for disabled switches

### ISSUE THREAD

**Issue by Tazaf** [webcat12345/ngx-ui-switch#399]
Hi!

First, thanks for this component! It's both complete and flexible 👍 

I've stumble upon a behavior that, I think, should not happen. As this issue's title says, the `beforeChange` observable is subscribed even when the switch is in a disabled state.

That doesn't seem to make much sense, as a disabled switch should be... well... disabled and thus should not trigger any event.

I think this issue is caused by the lack of `disabled` check in this line:
https://github.com/webcat12345/ngx-ui-switch/blob/4995c55d7842d52054871dbb6a0d19771e3d77fd/src/lib/ui-switch/ui-switch.component.ts#L157

which probably should be:
```ts
  onToggle(event: MouseEvent) {
    if (this.beforeChange && !this.disabled) {
      // ...
    } else {
      this.onClick(event);
    }
  }
```
I've seen that the `onClick` method does check for the `disabled` state, but in my case, it's too late since I'm doing some backend operation in the `beforeChange` observable ; my http call is made whatever my switch's `disabled` status is.

(Might be related to #375 and/or #353)

**Comment by cmckni3** [comment]
Yeah I don't think it was implemented correctly and I didn't test it (I don't use that functionality). I handle it in my application usually.

PRs welcome.

**Comment by cmckni3** [comment]
Check out 10.0.2
