### ISSUE TITLE
In firefox, unchecked label is shown to high

### ISSUE THREAD

**Issue by hrattls** [webcat12345/ngx-ui-switch#406]
In Firefox, unchecked label is shown to high / above component.

Cause:
In ui-switch.component.scss top of .switch-pane is set to -100%
For the checked state, top is set to 0, but this is not done when the switch is off.
I fixed this by adding the following to my css:

.switch .switch-pane {
  top: 0px;
}

Please fix in ui-switch.component.scss

**Comment by cmckni3** [comment]
Pull request please or I’ll get to it when I can.

**Comment by cmckni3** [comment]
#407

**Comment by cmckni3** [comment]
Looks good. Released in 9.0.2.
