### ISSUE TITLE
Seems incompatible with Angular 11

### ISSUE THREAD

**Issue by nelnico** [webcat12345/ngx-ui-switch#425]
I updated my Angular project from 10 to 11 before adding ngx-ui-switch.
(saying that because *maybe* I left out something when doing so manually)

After adding ngx-ui-switch as per the documentation,  the CLI gives the following error on `ng s`

```Error: node_modules/ngx-ui-switch/ui-switch/ui-switch.module.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of SharedModule, but could not 
be resolved to an NgModule class.

This likely means that the library (ngx-ui-switch/ui-switch/ui-switch.module) which declares UiSwitchModule has not been processed correctly by ngcc, 
or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.```

**Comment by cmckni3** [comment]
Yes, I haven't tested the component on ng 9, 10, or 11.

PRs welcome

**Comment by lcnvdl** [comment]
Hi! I'm having the same Issue. How can I fix it?

**Comment by cmckni3** [comment]
@lcnvdl send a PR with fixes for ng 9.

**Comment by imngular** [comment]
Does it work for angular 11 atm?

**Comment by cmckni3** [comment]
> Does it work for angular 11 atm?

Probably not due to ivy and Angular metadata incompatibility.

**Comment by tylerstarcher** [comment]
Is this going to be addressed? Seems there is a PR available for the upgrade as of 3 days ago. #427

**Comment by cmckni3** [comment]
Works for me on Angular 9.x, 10.x, and 11.2.7.

A workaround is to try [opting out of ivy](https://angular.io/guide/ivy#opting-out-of-ivy-in-version-9)

@josephtaylor reported the component works.

**Comment by cmckni3** [comment]
Tried with ivy explicitly enabled on 11.2.x and it works.

Feel free to reopen with a reproduction
