### ISSUE TITLE
Use switch on each row of a grid?

### ISSUE THREAD

**Issue by wolfbomb** [webcat12345/ngx-ui-switch#426]
How to use the switch on each reach of a grid with a loading indicator. Currently, when i tried to use it with the loading it will show the loading spinner on all rows instead of just the specific row that i am trying to set on or off. Can anyone suggest on how should it be done?

**Comment by cmckni3** [comment]
I don’t follow the relevance to the switch project.

**Comment by wolfbomb** [comment]
sorry if this has lead you to confusion. i found a way to implement this on a grid. thanks.
