### ISSUE TITLE
Support for Angular 12

### ISSUE THREAD

**Issue by DerZyklop** [webcat12345/ngx-ui-switch#435]
Angular 12 Update fives warning:

Package "ngx-ui-switch" has an incompatible peer dependency to "@angular/forms" (requires ">=5.0.0 <11.0.0" (extended), would install "12.0.4").

**Comment by cmckni3** [comment]
It works. I'll publish a new release with the updated peer dependencies.

**Comment by jasonverber** [comment]
@cmckni3 it looks like you updated the dependencies to indicate `@angular/common@">=5.0.0 <12.0.0"` which does not play nice with `@angular/common@12.1.1`.

**Comment by cmckni3** [comment]
> @cmckni3 it looks like you updated the dependencies to indicate `@angular/common@">=5.0.0 <12.0.0"` which does not play nice with `@angular/common@12.1.1`.

ah yes. Was trying to do too much. The `npm`/`yarn` warnings really don't matter.

Bigger issues are #439 and #437

**Comment by cmckni3** [comment]
Fixed
