### ISSUE TITLE
Running axe DevTools for accessibility shows issue 

### ISSUE THREAD

**Issue by ulisesmorenomassachusetts** [webcat12345/ngx-ui-switch#444]
ARIA attribute is not well supported on the element and the text content will be used instead: aria-label.

Issue Description
Ensures ARIA attributes are allowed for an element's role

Element location
.switch-label-unchecked
Element source
<span class="switch-label-unchecked" aria-label="NO">NO</span>

To solve this issue, you need to...
Fix the following:
ARIA attribute is not well supported on the element and the text content will be used instead: aria-label

**Comment by cmckni3** [comment]
any suggestions?

**Comment by cmckni3** [comment]
My guess is aria label and/or aria label checked might need to be added to a span element.

**Comment by miguelcanot** [comment]
Having the input of [aria-label] would be great to pass this value to the button element

**Comment by cmckni3** [comment]
shipped in 14.1.0
