### ISSUE TITLE
Support Angular 14

### ISSUE THREAD

**Issue by yashwanth4999** [webcat12345/ngx-ui-switch#460]
Hi @cmckni3 
Please give support for angular 14. we are using UI-Switch in the project and upgraded Angular to latest version.

**Comment by federicobenedetti** [comment]
Yep it would be great here too! :)

**Comment by vroussel35** [comment]
Has anyone found a workaround to support Angular 14? (waiting for the official ngx-ui-switch Angular 14 support)

**Comment by pliashkou** [comment]
Submitted a PR https://github.com/webcat12345/ngx-ui-switch/pull/461/files

**Comment by chrisstraw** [comment]
I got tired of waiting and created an Angular 14 library by copying the code.  If the owners respond and get the package updated, I might move back, but I don't want a repeat when Angular 15 releases.

https://www.npmjs.com/package/@outerlimitstech/ngx-ui-switch

**Comment by cmckni3** [comment]
> Submitted a PR https://github.com/webcat12345/ngx-ui-switch/pull/461/files

Merged. I’ll cut a release shortly

**Comment by cmckni3** [comment]
Is it not the case that it still works with newer versions but npm/yarn gives a warning? Does the npm/yarn warning cause CI to fail?

**Comment by cmckni3** [comment]
Released 14.0.1

**Comment by cmckni3** [comment]
`yarn publish` broke with 14.0.1 and 14.0.2. 14.0.3 is good to go.
