### ISSUE TITLE
ng14 install--peerDependency error specifying v10

### ISSUE THREAD

**Issue by stalsma** [webcat12345/ngx-ui-switch#462]
I am upgrading a project to ng14, and ran into an issue installing ui-switch.  It looks like the peerDependencies section in `src/lib/package.json` is still set to allow angular >= 10.  

```
  "peerDependencies": {
    "@angular/core": ">=10.0.0",
    "@angular/animations": ">=10.0.0",
    "@angular/common": ">=10.0.0",
    "@angular/forms": ">=10.0.0",
    "@angular/platform-browser": ">=10.0.0"
  },
```

My project specifically imports core and animations at v14:

```
  "dependencies": {
    "@angular/animations": "^14.2.0",
    "@angular/common": "14.2.0",
    "@angular/compiler": "14.2.0",
    "@angular/core": "14.2.0",
```

resulting in a dependencies error.  I was able to work around it (for dev):
```
npm install ngx-ui-switch --save --legacy-peer-deps
```

and everything compiles fine.  Is this simply an oversight?

Here's the raw error from npm:

```
While resolving: mlnpts@0.0.1-SNAPSHOT
Found: @angular/core@14.2.0
node_modules/@angular/core
  @angular/core@"14.2.0" from the root project
  peer @angular/core@">=10.0.0" from ngx-ui-switch@14.0.3
  node_modules/ngx-ui-switch
    ngx-ui-switch@"*" from the root project

Could not resolve dependency:
peer @angular/core@"14.2.2" from @angular/animations@14.2.2
node_modules/@angular/animations
  @angular/animations@"^14.2.0" from the root project
  peer @angular/animations@">=10.0.0" from ngx-ui-switch@14.0.3
  node_modules/ngx-ui-switch
    ngx-ui-switch@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by cmckni3** [comment]
Ugh. I hate the npm cli. I exclusively use yarn.

It’s sort of a bug sort of npm cli issue.

Have you tried using overrides in the package.json?

https://stackoverflow.com/a/67397982

**Comment by cmckni3** [comment]
Can also set the legacy peer

https://stackoverflow.com/a/66990138

what version of npm cli @stalsma?

**Comment by stalsma** [comment]
Using npm v8.15.0

It might be my config.  I had all the angular dependencies locked down to 14.2.0.  Except one:
"@angular/animations": "^14.2.0",

That installed 14.2.2.  When I locked animations down to 14.2.0, and then deleted node_modules and package_lock.json, everything installed fine.
