### ISSUE TITLE
Module build failed on Angular 15

### ISSUE THREAD

**Issue by Liam-VerifAction** [webcat12345/ngx-ui-switch#465]
Hi there, 

Recently upgraded from Angular 14 to 15 and get the following error when I try to compile

Error: Package path ./ui-switch.component.css is not exported from package  /node_modules/ngx-ui-switch 

Please let me if ngx-ui-switch supports Angular 15 and if not, when would it be able to

**Comment by shrinarpat** [comment]
@Liam-VerifAction  - Did you found the solution for this error - I'm also getting the same error in Angular 15 with UI-Switch

**Comment by Liam-VerifAction** [comment]
@shrinarpat  Hi, yes I eventually found the same solution - thanks!

**Comment by cmckni3** [comment]
> Hi there,
> 
> Recently upgraded from Angular 14 to 15 and get the following error when I try to compile
> 
> Error: Package path ./ui-switch.component.css is not exported from package /node_modules/ngx-ui-switch
> 
> Please let me if ngx-ui-switch supports Angular 15 and if not, when would it be able to

Is the import correct in angular.json @Liam-VerifAction or does the css import not work at all?

**Comment by cmckni3** [comment]
> @Liam-VerifAction - Did you find the solution for this error - I'm also getting the same error in Angular 15 with UI-Switch
> 
> Solution: - when I imported the stylesheet like this in my scss file it works -
> 
> `@import "../../node_modules/ngx-ui-switch/ui-switch.component.scss";`


yeah can either reference the node_modules folder this way or remove the `~`. The `~` meaning "the node_modules directory" was deprecated in ng 15.

https://stackoverflow.com/questions/73853771/scss-usage-of-in-imports-is-deprecated-angular-vscode
