### ISSUE TITLE
reverse option does not work

### ISSUE THREAD

**Issue by blazekv** [webcat12345/ngx-ui-switch#473]
It looks like that reverse option does not work at all. Or maybe I got wrong purpose of that feature. I thought that if reverse is set to true then checked state is pin on left and uncheck is right. But reverse set to true did not do that. It could be replicated even on demo and Stackblitz sample project.

**Comment by cmckni3** [comment]
Yep, appears broken due to an Angular upgrade at some point. On the demo, one of them works and one doesn't.

Investigating

**Comment by blazekv** [comment]
@cmckni3 please look at my pull request. I look into it and maybe I found the problem.
