### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by wojciechpolak** [webcat12345/ngx-ui-switch#58]
Hi,
I'm trying ngx-ui-switch 1.3.5 with Angular 4.1.3 and webpack 2.6.1.

In my shared.module I have:
`import { UiSwitchModule } from 'ngx-ui-switch/src';`
and I import and export it in that shared.module. I got the following error while building AOT:

```
ERROR in ./~/ngx-ui-switch/src/index.ts
Module parse failed: /[PATH]/node_modules/ngx-ui-switch/src/index.ts Unexpected character '@' (5:0)
You may need an appropriate loader to handle this file type.
| import { UiSwitchComponent } from './ui-switch.component';
| 
| @NgModule({
|     declarations: [UiSwitchComponent],
|     exports: [UiSwitchComponent]
 @ ./src/app/shared/shared.module.ts 45:0-51
...
```

Without AOT and by importing just from `ngx-ui-switch` instead of `ngx-ui-switch/src` - all builds and works fine. What am I missing?

**Comment by webcat12345** [comment]
@wojciechpolak , why you did declaration UiSwitchComponent inside your module and exported it?

Actually one component can be part of declaration of one module inside project.
UiSwitchComponent is the part of UiSwitchModule, you just need to use component by importing UiSwitchModule inside your module.

**Comment by wojciechpolak** [comment]
Not a declaration. Shared module imports and exports UiSwitchModule (a typical case). So my other components deal only with my shared module.

```
...
import { UiSwitchModule } from 'ngx-ui-switch/src';
...
@NgModule({
    imports: [
        ...
        UiSwitchModule,
    ],
    exports: [
        ...
        UiSwitchModule,
    ]
...
})
export class SharedModule {}
```

**Comment by webcat12345** [comment]
I just tried that on same environment it works fine for me. Could you please create plunker for that?

**Comment by wojciechpolak** [comment]
Ok, I found the source of the problem. The key was the message "You may need an appropriate loader to handle this file type". In my Webpack conf I have excluded `node_modules`. And here we import TypeScript via `ngx-ui-switch/src`. Adding an exception in include or removing exclude solved this issue. My original webpack conf:
```
...
            module: {
                rules: [
                    {
                        test: /\.ts$/,
                        exclude: /node_modules/,
                        use: [
                            {
                                loader: 'awesome-typescript-loader'
                            },
                            {
                                loader: 'angular2-template-loader'
                            }
                        ]
                    },
```
