### ISSUE TITLE
Attribute `checked` is always set to `true`

### ISSUE THREAD

**Issue by morkro** [webcat12345/ngx-ui-switch#60]
Hey, great component here! 👍 

I am trying to get the `checked` attribute to work for quite some time now, and looking at the source code it doesn't seem to be implemented? 

The value is [static](https://github.com/webcat12345/ngx-ui-switch/blob/master/src/ui-switch.component.ts#L14) and there is also no `@Input()` applied? Maybe I am getting this completely wrong, but no matter what I try the `checked` attribute always falls back to `true`.

**Comment by webcat12345** [comment]
`@Input()` is implemented [here](https://github.com/webcat12345/ngx-ui-switch/blob/master/src/ui-switch.component.ts#L119) .

And short demo for sync `checked` attribute here goes.

```
<ui-switch [checked]="cust" (change)="onChange($event)"></ui-switch>

<h2>{{cust}}</h2>

<button class="btn btn-primary" (click)="onSwitch()">Change</button>
```

```
  cust = false;
  onChange(event): void {
    console.log(event);
  }
  onSwitch(): void {
    this.cust = !this.cust;
  }
```

**Comment by morkro** [comment]
Thanks for the quick reply. You are right, it should actually work. 
Guess my issue is somewhere else in my codebase. 🤔

**Comment by webcat12345** [comment]
@morkro Please let me know when your issue is solved so I can close this issue. Thanks.

**Comment by morkro** [comment]
The issue has not been resolved for me. Regardless of what I add to `[checked]` it always defaults to `true`. It seems like internally the values are correct, but somehow the `.checked` class is still applied to the element.

**Comment by webcat12345** [comment]
Reopen issue when you can provide example.
