### ISSUE TITLE
Please add a @NgModule annotation. in Angular4 with AoT build

### ISSUE THREAD

**Issue by vincent-cm** [webcat12345/ngx-ui-switch#61]
Error: Unexpected value 'UiSwitchModule in /node_modules/ngx-ui-switch/dist/index.d.ts' imported by the module

**Comment by webcat12345** [comment]
@vincent-cm  Could you please make plunker so I can check error?

**Comment by webcat12345** [comment]
Reopen issue when you can provide example.
