### ISSUE TITLE
Error: Cannot find module 'ngx-ui-switch/src' in angular-cli with angular universal

### ISSUE THREAD

**Issue by Sathishchary** [webcat12345/ngx-ui-switch#62]
Its working with angular cli, but after converting my project to angular cli with angular universal. its showing the error
Error: Cannot find module 'ngx-ui-switch/src'
```
    throw err;
    ^
   Error: Cannot find module 'ngx-ui-switch/src'
    at Function.Module._resolveFilename (module.js:469:15)
```
using :
"ngx-ui-switch": "^1.3.5",
import { UiSwitchModule } from 'ngx-ui-switch/src';
@NgModule({
 imports: [UiSwitchModule]
......
})

**Comment by webcat12345** [comment]
Currently its not supporting angular universal. Closing issue.
