### ISSUE TITLE
Cannot install through NPM

### ISSUE THREAD

**Issue by JustinSchneider** [webcat12345/ngx-ui-switch#99]
Trying to install using command:
`npm install ngx-ui-switch --save`

gets the error:

> npm ERR! path C:\Projects\FormsDesigner\node_modules\ngx-ui-switch
> npm ERR! code ENOENT
> npm ERR! errno -4058
> npm ERR! syscall rename
> npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Projects\FormsDesigner\node_modules\ngx-ui-switch' -> 'C:\Projects\FormsDesigner\node_modules\.ngx-ui-switch.DELETE'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\_USER_NAME_\AppData\Roaming\npm-cache\_logs\2017-06-30T13_33_06_207Z-debug.log

The complete log relevant section is this exact same message.

**Comment by webcat12345** [comment]
npm install should works. Please provide plunker example.

**Comment by webcat12345** [comment]
Reopen issue when you can provide example.
